# Generated by Django 5.1.5 on 2025-03-11 14:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApuGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoSubido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='uploads/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('modelo_destino', models.CharField(choices=[('ProyectoNuevo', 'Proyecto Nuevo'), ('CategoriaNuevo', 'Categoría Nueva'), ('CostoNuevo', 'Costo Nuevo'), ('Adquisiciones', 'Adquisiciones'), ('Cantidades', 'Cantidades'), ('MaterialesOtros', 'Materiales Otros'), ('EquiposConstruccion', 'Equipos Construcción'), ('ManoObra', 'Mano Obra'), ('EspecificoCategoria', 'Especifico Categoria'), ('ApuEspecifico', 'Apu Especifico'), ('ApuGeneral', 'Apu General'), ('StaffEnami', 'Staff Enami')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoNuevo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaNuevo',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('final', models.BooleanField(default=False)),
                ('total_costo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('id_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='proyectoApp.categorianuevo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='proyectoApp.proyectonuevo')),
            ],
        ),
        migrations.CreateModel(
            name='Cantidades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantidades', to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='Adquisiciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_origen', models.CharField(max_length=50)),
                ('tipo_categoria', models.CharField(max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='CostoNuevo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='DatosEP',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hh_profesionales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_hh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_ep', to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='DatosOtrosEP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comprador', models.IntegerField()),
                ('dedicacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_pax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gestiones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('viajes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_otros_ep', to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='EquiposConstruccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_maquina_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_maquina_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_horas_maquina', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='EspecificoCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dedicacion', models.DecimalField(decimal_places=2, help_text='Porcentaje de dedicación (0-100)', max_digits=5)),
                ('duracion', models.DecimalField(decimal_places=2, help_text='Duración en meses', max_digits=5)),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo en dólares al mes', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=15)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='ManoObra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horas_hombre_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rendimiento', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('horas_hombre_final', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('cantidad_horas_hombre', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('tarifas_usd_hh_mod', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('costo_hombre_hora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_hh', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('total_usd_mod', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('total_usd_v1', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('total_usd_v2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='ApuEspecifico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('id_apu_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apus_especificos', to='proyectoApp.apugeneral')),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apus_especifico', to='proyectoApp.categorianuevo')),
                ('id_mano_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apus_especificos', to='proyectoApp.manoobra')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialesOtros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='StaffEnami',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dotacion', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField()),
                ('factor_utilizacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_horas_hombre', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_enami', to='proyectoApp.categorianuevo')),
            ],
        ),
    ]
