# Generated by Django 5.1.5 on 2025-03-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manoobra',
            old_name='total_usd_v1',
            new_name='total_usd',
        ),
    ]
