# Generated by Django 5.1.5 on 2025-03-11 17:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0002_rename_total_usd_v1_manoobra_total_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='manoobra',
            name='tarifa_usd_hh_equipos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='manoobra',
            name='total_usd_equipos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.88'), editable=False, max_digits=10),
        ),
    ]
