# Generated by Django 5.1.5 on 2025-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0003_manoobra_tarifa_usd_hh_equipos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquisiciones',
            name='crecimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
