# Generated by Django 5.1.5 on 2025-03-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0006_remove_manoobra_total_usd_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoSubcontrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_laboral_indirecto_usd_hh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_usd_indirectos_contratista', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usd_por_unidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fc_subcontrato', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usd_total_subcontrato', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_contrato_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_contrato_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.categorianuevo')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionMateriales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_suministro', models.CharField(max_length=100)),
                ('tipo_moneda', models.CharField(max_length=3)),
                ('pais_entrega', models.CharField(max_length=100)),
                ('fecha_cotizacion_referencia', models.DateField()),
                ('cotizacion_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion_clp', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factor_correccion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('moneda_aplicada', models.CharField(max_length=10)),
                ('origen_precio', models.CharField(max_length=100)),
                ('cotizacion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_origen', models.CharField(max_length=10)),
                ('tasa_cambio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.categorianuevo')),
            ],
        ),
    ]
