# Generated by Django 5.1.5 on 2025-03-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0008_alter_archivosubido_modelo_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionmateriales',
            name='moneda_aplicada',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
