# Generated by Django 5.1.5 on 2025-03-17 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0009_alter_cotizacionmateriales_moneda_aplicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosubido',
            name='modelo_destino',
            field=models.CharField(choices=[('ProyectoNuevo', 'Proyecto Nuevo'), ('CategoriaNuevo', 'Categoría Nueva'), ('CostoNuevo', 'Costo Nuevo'), ('Adquisiciones', 'Adquisiciones'), ('Cantidades', 'Cantidades'), ('MaterialesOtros', 'Materiales Otros'), ('EquiposConstruccion', 'Equipos Construcción'), ('ManoObra', 'Mano Obra'), ('EspecificoCategoria', 'Especifico Categoria'), ('ApuEspecifico', 'Apu Especifico'), ('ApuGeneral', 'Apu General'), ('StaffEnami', 'Staff Enami'), ('ContratoSubcontrato', 'Contrato Subcontrato'), ('CotizacionMateriales', 'Cotizacion Materiales'), ('IngenieriaDetallesContraparte', 'Ingenieria Detalles Contraparte')], max_length=50),
        ),
        migrations.CreateModel(
            name='IngenieriaDetallesContraparte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('UF', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MB', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.categorianuevo')),
            ],
        ),
    ]
