# Generated by Django 5.1.5 on 2025-03-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0012_alter_archivosubido_modelo_destino_dueno'),
    ]

    operations = [
        migrations.CreateModel(
            name='MB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mb', models.DecimalField(decimal_places=6, max_digits=15)),
                ('fc', models.DecimalField(decimal_places=6, max_digits=15)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='archivosubido',
            name='modelo_destino',
            field=models.CharField(choices=[('ProyectoNuevo', 'Proyecto Nuevo'), ('CategoriaNuevo', 'Categoría Nueva'), ('CostoNuevo', 'Costo Nuevo'), ('Adquisiciones', 'Adquisiciones'), ('Cantidades', 'Cantidades'), ('MaterialesOtros', 'Materiales Otros'), ('EquiposConstruccion', 'Equipos Construcción'), ('ManoObra', 'Mano Obra'), ('EspecificoCategoria', 'Especifico Categoria'), ('ApuEspecifico', 'Apu Especifico'), ('ApuGeneral', 'Apu General'), ('StaffEnami', 'Staff Enami'), ('ContratoSubcontrato', 'Contrato Subcontrato'), ('CotizacionMateriales', 'Cotizacion Materiales'), ('IngenieriaDetallesContraparte', 'Ingenieria Detalles Contraparte'), ('GestionPermisos', 'Gestion Permisos'), ('Dueno', 'Dueño'), ('MB', 'MB'), ('AdministracionSupervision', 'Administracion Supervision'), ('PersonalIndirectoContratista', 'Personal Indirecto Contratista')], max_length=50),
        ),
        migrations.CreateModel(
            name='AdministracionSupervision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario_clp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor_uso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_u_persona', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total_clp', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('costo_total_us', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('costo_total_mb', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.categorianuevo')),
                ('mb_seleccionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.mb')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalIndirectoContratista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(max_length=50)),
                ('unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hh_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plazo_mes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_hh', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('precio_unitario_clp_hh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tarifa_usd_hh', models.DecimalField(decimal_places=6, editable=False, max_digits=15)),
                ('costo_total_clp', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('costo_total_us', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('costo_total_mb', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.categorianuevo')),
                ('mb_seleccionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.mb')),
            ],
        ),
    ]
