# Generated by Django 5.1.5 on 2025-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0013_mb_alter_archivosubido_modelo_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalindirectocontratista',
            name='unidad',
            field=models.CharField(max_length=255),
        ),
    ]
