# Generated by Django 5.1.5 on 2025-03-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0014_alter_personalindirectocontratista_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administracionsupervision',
            name='unidad',
            field=models.CharField(max_length=255),
        ),
    ]
