# Generated by Django 5.1.5 on 2025-03-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0017_alter_archivosubido_modelo_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciosapoyo',
            name='mb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.mb'),
        ),
    ]
