# Generated by Django 5.1.5 on 2025-03-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0019_alter_otrosadm_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionpermisos',
            name='MB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.mb'),
        ),
    ]
