# Generated by Django 5.1.5 on 2025-03-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0021_alter_ingenieriadetallescontraparte_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingenieriadetallescontraparte',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
