# Generated by Django 5.1.5 on 2025-03-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0022_ingenieriadetallescontraparte_total_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mb',
            name='anio',
            field=models.DateField(),
        ),
    ]
