# Generated by Django 5.1.5 on 2025-03-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0026_alter_archivosubido_modelo_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosubido',
            name='archivo',
            field=models.FileField(upload_to='uploads/ExcelUnico/'),
        ),
        migrations.AlterField(
            model_name='archivosubido',
            name='modelo_destino',
            field=models.CharField(choices=[('ExcelUnico', 'Excel Unico')], default='ExcelUnico', max_length=50),
        ),
    ]
