# Generated by Django 5.1.5 on 2025-03-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0027_alter_archivosubido_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosubido',
            name='archivo',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='archivosubido',
            name='modelo_destino',
            field=models.CharField(choices=[('ProyectoNuevo', 'Proyecto Nuevo'), ('CategoriaNuevo', 'Categoría Nueva'), ('CostoNuevo', 'Costo Nuevo'), ('Adquisiciones', 'Adquisiciones'), ('Cantidades', 'Cantidades'), ('MaterialesOtros', 'Materiales Otros'), ('EquiposConstruccion', 'Equipos Construcción'), ('ManoObra', 'Mano Obra'), ('EspecificoCategoria', 'Especifico Categoria'), ('ApuEspecifico', 'Apu Especifico'), ('ApuGeneral', 'Apu General'), ('StaffEnami', 'Staff Enami'), ('ContratoSubcontrato', 'Contrato Subcontrato'), ('CotizacionMateriales', 'Cotizacion Materiales'), ('IngenieriaDetallesContraparte', 'Ingenieria Detalles Contraparte'), ('GestionPermisos', 'Gestion Permisos'), ('Dueno', 'Dueño'), ('MB', 'MB'), ('AdministracionSupervision', 'Administracion Supervision'), ('PersonalIndirectoContratista', 'Personal Indirecto Contratista'), ('ServiciosApoyo', 'Servicios Apoyo'), ('OtrosADM', 'Otros ADM'), ('AdministrativoFinanciero', 'Administrativo Financiero')], max_length=50),
        ),
    ]
