# Generated by Django 5.1.5 on 2025-03-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0028_alter_archivosubido_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mb',
            name='anio',
            field=models.DateField(unique=True),
        ),
    ]
