# Generated by Django 5.1.5 on 2025-03-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0029_alter_mb_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mb',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
