# Generated by Django 5.1.5 on 2025-03-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0030_alter_mb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adquisiciones',
            name='flete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='adquisiciones',
            name='total_con_flete',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
