# Generated by Django 5.1.5 on 2025-03-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0031_adquisiciones_flete_adquisiciones_total_con_flete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialesotros',
            name='flete_unitario',
        ),
        migrations.AddField(
            model_name='cotizacionmateriales',
            name='flete_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
