# Generated by Django 5.1.5 on 2025-04-02 18:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0032_remove_materialesotros_flete_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoobra',
            name='tarifa_usd_hh_equipos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
