# Generated by Django 5.1.5 on 2025-04-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0034_categorianuevo_categoria_relacionada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorianuevo',
            name='categoria_relacionada',
        ),
        migrations.AddField(
            model_name='categorianuevo',
            name='categoria_relacionada_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
