# Generated by Django 5.1.5 on 2025-04-03 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0035_remove_categorianuevo_categoria_relacionada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorianuevo',
            old_name='categoria_relacionada_id',
            new_name='categoria_relacionada',
        ),
    ]
