# Generated by Django 5.1.5 on 2025-04-09 20:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0038_alter_archivosubido_modelo_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectonuevo',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=20),
        ),
    ]
