# Generated by Django 5.1.5 on 2025-04-17 16:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0039_proyectonuevo_costo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectonuevo',
            name='porcentaje_contingencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='proyectonuevo',
            name='porcentaje_utilidades',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
