# Generated by Django 5.1.5 on 2025-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0040_proyectonuevo_porcentaje_contingencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestionpermisos',
            name='MB',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
