# Generated by Django 5.1.5 on 2025-04-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0041_alter_gestionpermisos_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrosadm',
            name='total_clp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
