# Generated by Django 5.1.5 on 2025-04-28 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0042_otrosadm_total_clp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestionpermisos',
            name='total_clp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='gestionpermisos',
            name='MB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectoApp.mb'),
        ),
    ]
